### ISSUE TITLE
Do we need pyarrow?

### ISSUE THREAD

**Issue by vukics** [vukics/Wigner_Time#38]
The installation of pyarrow in `poetry install` exits with an error on a Windows 11 box (Lab2machine)

Earlier, I got a similar error with numpy, but after installing build tools, it installed fine. However, the error persists with pyarrow.

What do we need pyarrow for?

**Comment by light-matters** [comment]
Generally speaking, it's good to have as it (I believe) enhances `pandas` performance. It's not essential essential and so we could maybe make it an optional dependency for our 'users'. 

In the lab though, I think we should have it because it helps (is necessary?) for exporting `to_parquet`. This is much more efficient than other formats, like pickle. Death to pickle! ...
